// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "D:/tori/private/TypeScript 直播班/enjoyment-hotel/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}