// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "F:/程式設計相關/TypeScript直播班/team/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}