const interopDefault = r => r.default || r || [];
const styles = {
  "node_modules/nuxt/dist/app/entry.js": () => import('./_nuxt/entry-styles.AvdSnySA.mjs').then(interopDefault),
  "pages/login/index.vue": () => import('./_nuxt/index-styles.v_3mAWQz.mjs').then(interopDefault),
  "pages/index.vue": () => import('./_nuxt/index-styles.GTQPJaLS.mjs').then(interopDefault),
  "pages/reserve.vue": () => import('./_nuxt/reserve-styles.B42a8v2n.mjs').then(interopDefault),
  "pages/confirmation.vue": () => import('./_nuxt/confirmation-styles.gsX5XeL7.mjs').then(interopDefault),
  "pages/guideline.vue": () => import('./_nuxt/guideline-styles.IwWZ7taZ.mjs').then(interopDefault),
  "pages/room/[id].vue": () => import('./_nuxt/_id_-styles.PxQ5zqJk.mjs').then(interopDefault),
  "pages/user/index.vue": () => import('./_nuxt/index-styles.mVY9OcFd.mjs').then(interopDefault),
  "pages/rooms.vue": () => import('./_nuxt/rooms-styles.YrUqd7GX.mjs').then(interopDefault),
  "pages/signup.vue": () => import('./_nuxt/signup-styles.O83NCvJo.mjs').then(interopDefault),
  "pages/user/orders.vue": () => import('./_nuxt/orders-styles.2rg-HuBx.mjs').then(interopDefault),
  "node_modules/nuxt-icon/dist/runtime/Icon.vue": () => import('./_nuxt/Icon-styles.cuKUCxHd.mjs').then(interopDefault),
  "node_modules/nuxt-icon/dist/runtime/IconCSS.vue": () => import('./_nuxt/IconCSS-styles.SAAlqMtQ.mjs').then(interopDefault),
  "node_modules/nuxt-icon/dist/runtime/IconCSS.vue?vue&type=style&index=0&scoped=41e8d397&lang.css": () => import('./_nuxt/IconCSS-styles.SAAlqMtQ.mjs').then(interopDefault),
  "node_modules/nuxt-icon/dist/runtime/Icon.vue?vue&type=style&index=0&scoped=bd832875&lang.css": () => import('./_nuxt/Icon-styles.cuKUCxHd.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue": () => import('./_nuxt/error-404-styles.G0X74LJU.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue": () => import('./_nuxt/error-500-styles.vPkMidp2.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=ccd3db62&lang.css": () => import('./_nuxt/error-404-styles.G0X74LJU.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=df79c84d&lang.css": () => import('./_nuxt/error-500-styles.vPkMidp2.mjs').then(interopDefault),
  "pages/confirmation.vue?vue&type=style&index=0&scoped=00dc4a5c&lang.scss": () => import('./_nuxt/confirmation-styles.gsX5XeL7.mjs').then(interopDefault),
  "pages/reserve.vue?vue&type=style&index=0&scoped=d9d2f249&lang.scss": () => import('./_nuxt/reserve-styles.B42a8v2n.mjs').then(interopDefault),
  "pages/login/index.vue?vue&type=style&index=0&scoped=499c2476&lang.scss": () => import('./_nuxt/index-styles.v_3mAWQz.mjs').then(interopDefault),
  "pages/room/[id].vue?vue&type=style&index=0&scoped=1cdfcbca&lang.scss": () => import('./_nuxt/_id_-styles.PxQ5zqJk.mjs').then(interopDefault),
  "pages/guideline.vue?vue&type=style&index=0&scoped=08909a85&lang.scss": () => import('./_nuxt/guideline-styles.IwWZ7taZ.mjs').then(interopDefault),
  "pages/rooms.vue?vue&type=style&index=0&scoped=86dbf8c9&lang.scss": () => import('./_nuxt/rooms-styles.YrUqd7GX.mjs').then(interopDefault),
  "pages/index.vue?vue&type=style&index=0&scoped=b6867328&lang.scss": () => import('./_nuxt/index-styles.GTQPJaLS.mjs').then(interopDefault),
  "app.vue?vue&type=style&index=0&lang.scss": () => import('./_nuxt/app.vue._4pZIBH8.mjs').then(interopDefault),
  "components/page/PageDefault.vue": () => import('./_nuxt/PageDefault-styles.xn-noXAJ.mjs').then(interopDefault),
  "components/rooms/TheRoomsInfo.vue": () => import('./_nuxt/TheRoomsInfo-styles.gxZk7p8D.mjs').then(interopDefault),
  "pages/signup.vue?vue&type=style&index=0&scoped=7f611229&lang.scss": () => import('./_nuxt/signup-styles.O83NCvJo.mjs').then(interopDefault),
  "pages/user/orders.vue?vue&type=style&index=0&scoped=8988a966&lang.scss": () => import('./_nuxt/orders-styles.2rg-HuBx.mjs').then(interopDefault),
  "pages/user/index.vue?vue&type=style&index=0&scoped=7c7ea3ce&lang.scss": () => import('./_nuxt/index-styles.mVY9OcFd.mjs').then(interopDefault),
  "layouts/h-f-spl.vue": () => import('./_nuxt/h-f-spl-styles.TpwBI75Q.mjs').then(interopDefault),
  "layouts/h-bg-f.vue": () => import('./_nuxt/h-bg-f-styles.-puIbkw4.mjs').then(interopDefault),
  "layouts/h-logo-f-spl.vue": () => import('./_nuxt/h-logo-f-spl-styles.KOW1rjDl.mjs').then(interopDefault),
  "layouts/h-logo-f-no.vue": () => import('./_nuxt/h-logo-f-no-styles.fgqGRUGp.mjs').then(interopDefault),
  "layouts/default.vue": () => import('./_nuxt/default-styles.-zUuO8jg.mjs').then(interopDefault),
  "layouts/h-bg-f-spl.vue": () => import('./_nuxt/h-bg-f-spl-styles.zeardQNN.mjs').then(interopDefault),
  "components/rooms/TheRoomsInfo.vue?vue&type=style&index=0&scoped=96942fbc&lang.scss": () => import('./_nuxt/TheRoomsInfo-styles.gxZk7p8D.mjs').then(interopDefault),
  "components/page/PageDefault.vue?vue&type=style&index=0&scoped=56acb0cb&lang.scss": () => import('./_nuxt/PageDefault-styles.xn-noXAJ.mjs').then(interopDefault),
  "components/page/PageHeader.vue": () => import('./_nuxt/PageHeader-styles.aGSHqyip.mjs').then(interopDefault),
  "components/page/PageFooter.vue": () => import('./_nuxt/PageFooter-styles.g1bqzsg1.mjs').then(interopDefault),
  "layouts/h-f-spl.vue?vue&type=style&index=0&scoped=b7aab6c8&lang.scss": () => import('./_nuxt/h-f-spl-styles.TpwBI75Q.mjs').then(interopDefault),
  "layouts/h-bg-f.vue?vue&type=style&index=0&scoped=4bb03c1d&lang.scss": () => import('./_nuxt/h-bg-f-styles.-puIbkw4.mjs').then(interopDefault),
  "layouts/h-logo-f-spl.vue?vue&type=style&index=0&scoped=9b5b93a5&lang.scss": () => import('./_nuxt/h-logo-f-spl-styles.KOW1rjDl.mjs').then(interopDefault),
  "layouts/default.vue?vue&type=style&index=0&scoped=7a01b03d&lang.scss": () => import('./_nuxt/default-styles.-zUuO8jg.mjs').then(interopDefault),
  "layouts/h-logo-f-no.vue?vue&type=style&index=0&scoped=86f6bb0b&lang.scss": () => import('./_nuxt/h-logo-f-no-styles.fgqGRUGp.mjs').then(interopDefault),
  "layouts/h-bg-f-spl.vue?vue&type=style&index=0&scoped=90753f0e&lang.scss": () => import('./_nuxt/h-bg-f-spl-styles.zeardQNN.mjs').then(interopDefault),
  "components/page/PageHeader.vue?vue&type=style&index=0&scoped=ece18b7e&lang.scss": () => import('./_nuxt/PageHeader-styles.aGSHqyip.mjs').then(interopDefault),
  "components/page/PageFooter.vue?vue&type=style&index=0&scoped=d7b22c37&lang.scss": () => import('./_nuxt/PageFooter-styles.g1bqzsg1.mjs').then(interopDefault)
};

export { styles as default };
//# sourceMappingURL=styles.mjs.map
